
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EREN
 */
public class SiparisUygulamasiReeel extends javax.swing.JFrame {
    Map<String,Integer> siparisler = new LinkedHashMap<String,Integer>();
    

    /**
     * Creates new form SiparisUygulamasiReeel
     */
    public SiparisUygulamasiReeel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLabel();
        lahmacun = new javax.swing.JCheckBox();
        kebap = new javax.swing.JCheckBox();
        kofte = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        goster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        menu.setText("Menü");

        lahmacun.setText("Lahmacun - 60");

        kebap.setText("Kebap - 100");

        kofte.setText("Köfte - 80");

        ayran.setText("Ayran - 20");

        goster.setText("Göster");
        goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kofte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kebap, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(ayran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lahmacun))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lahmacun)
                .addGap(18, 18, 18)
                .addComponent(kebap)
                .addGap(18, 18, 18)
                .addComponent(kofte)
                .addGap(18, 18, 18)
                .addComponent(ayran)
                .addGap(41, 41, 41)
                .addComponent(goster)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void siparisleriGoster(){
        String message = "";
        int tutar = 0;
        
        if(siparisler.isEmpty())
        {
            message = "Siparişiniz bulunmamaktadır!";
        }
        else
        {
            message += "Siparişler: \n";
            for(Map.Entry<String, Integer> entry : siparisler.entrySet()){
                message += entry.getKey() + "\n";
                tutar += entry.getValue();
            }
            message += "Toplam tutar : " + tutar;
        }
        JOptionPane.showMessageDialog(this, message);
    }
    private void gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gosterActionPerformed
        if(lahmacun.isSelected())
        {
            siparisler.put("Lahmacun",60);
        }
        else
        {
            siparisler.remove("Lahmacun");
        }
        if(kebap.isSelected())
        {
            siparisler.put("Kebap",100);
        }
        else
        {
            siparisler.remove("Kebap");
        }
        if(kofte.isSelected())
        {
            siparisler.put("Köfte",80);
        }
        else
        {
            siparisler.remove("Köfte");
        }
        if(ayran.isSelected())
        {
            siparisler.put("Ayran",20);
        }
        else
        {
            siparisler.remove("Ayran");
        }
        siparisleriGoster();
    }//GEN-LAST:event_gosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasiReeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasiReeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasiReeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasiReeel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasiReeel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JButton goster;
    private javax.swing.JCheckBox kebap;
    private javax.swing.JCheckBox kofte;
    private javax.swing.JCheckBox lahmacun;
    private javax.swing.JLabel menu;
    // End of variables declaration//GEN-END:variables
}
